### ISSUE TITLE
CONTRIBUTIONS.md

### ISSUE THREAD

**Issue by mezbaulanam** [UndeadMe/React-User-Panel#2]
Interested to contribute to this awesome project, But couldn't find a valid CONTRIBUTIONS.md file :)

**Comment by UndeadMe** [comment]
why u need CONTRIBUTIONS.md file ?

**Comment by mezbaulanam** [comment]
That helps github users understand in what parts of the public repo, they can contribute to-

**Comment by UndeadMe** [comment]
sure,
if you wanna contribute you can checkout the [v1 branch](https://github.com/UndeadMe/React-User-Panel/tree/v1)

**Comment by mezbaulanam** [comment]
thanks
